****************************************************************************
*  Launch.prg   
*  -- Web Connection Application Launch Helper
**********************************************************
***  This is an optional tool to help you launch Web Connection
***  applications more easily. It's completely optional but makes
***  easier to launch especially modes that require starting up support
***  applications like IISExpress and/or Browser sync.
***
***  You can still do:   
***
***        DO VueMain.prg 
***
***  and then manually switch to a browser and or start IISExpress
***  or BrowserSync manually.
***
***  Function: Launches a Web Connection Server in various modes
***            and opens a Web page to the appropriate Web location.
*** 
***      Pass:  lcType:         "IIS"
***                             "IISEXPRESS"
***                             "WEBCONNECTIONWEBSERVER"
***                             "NONE" or "SERVER"
*** 
***             llNoBrowser:    If .T. doesn't open a browser window
*** 
***  Examples:
*** 
***  LAUNCH()                        - Launches IIS and opens browser
***  LAUNCH("IISEXPRESS")            - Launches IIS Express & opens browser
***  LAUNCH("WEBCONNECTIONWEBSERVER")            - Launches local .NET Core Web Server
***  LAUNCH("IIS",.T.)               - Launch IIS and don't open browser 
***  LAUNCH("NONE")                  - Just launch the Server
*********************************************************************************
LPARAMETER lcType, llNoBrowser
LOCAL lcUrl, lcLocalUrl, llIsIISExpress, lcAppName, ;
      lcScriptMap, lcFiles, lcWcPath, lcVirtual

*** Generated Defaults
lcVirtual = "vue"
lcAppName = "vue"
lcScriptMap = "wcvue"
lcWcPath = ADDBS(LOWER(SYS(5) + CURDIR()))
lcWebPath = LOWER(FULLPATH("..\web"))
	
lcDotnetServerPath = lower(FULLPATH("..\WebConnectionWebServer\"))
lcServerName = "IIS"
lcServerCommand = ""
lcIisDomain = "localhost"
llIisExpress = .F.

IF VARTYPE(lcType) = "L"
   IF llIISExpress 
      lcType = "IISEXPRESS"
   ELSE
      lcType = "IIS"
   ENDIF
ELSE
   lcType = UPPER(lcType)
   DO CASE 
      CASE lcType = "IIS"
      CASE lcType = "IISEXPRESS"      
      	lcServerName = "IIS Express"
     CASE lcType == "DOTNETCORE" OR lcType == "WEBCONNECTIONWEBSERVER"
	lcServerName = ".NET Core Web Connection Web Server"
        lcType = "WEBCONNECTIONWEBSERVER"
      CASE lcType = "NONE" OR lcType = "SERVER"
      	lcServerName = "NONE"
      	llNoBrowser = .T.
        lcType = "IIS"  && doesn't launch anyting
      CASE lcType = "HELP"
       DO Console WITH "GOURL","https://webconnection.west-wind.com/docs/_5h60q6vu5.htm#launch-modes"
       RETURN
   ENDCASE
ENDIF

llNoBrowser = IIF(EMPTY(llNoBrowser),.f.,.t.)

CLEAR

********************************
*** SET UP ENVIRONMENT AND PATHS
********************************

*** Optionally release everything before you run
* RELEASE ALL
* SET PROCEDURE TO
* SET CLASSLIB TO

*** Reference Web Connection Folders 
*** so Web Connection Framework programs can be found
*** GENERATED BY PROJECT WIZARD: Change if paths change
SET PATH TO (lcWcPath + "classes") ADDITIVE
SET PATH TO (lcWcPath) ADDITIVE
SET PATH TO (lcWcPath + "tools") ADDITIVE


***********************************************************
*** START UP WEB SERVER (IIS Express and BrowserSync only)
***********************************************************
lcUrl = "http://localhost/" + lcVirtual
lcServerCommand = ""


IF lcType == "IISEXPRESS"
    *** Launch IIS Express on Port 7000
    DO CONSOLE WITH "IISEXPRESS",lcWebPath,7000,"/","NONAVIGATE"    
    lcUrl = STRTRAN(lcUrl,"localhost/" + lcVirtual,"localhost:7000")
ENDIF
IF lcType == "IIS"
   IF !EMPTY(lcIisDomain)
       lcUrl = STRTRAN(lcUrl,"/localhost/","/" + lcIisDomain +"/")
   ENDIF
ENDIF
IF lcType == "WEBCONNECTIONWEBSERVER"
   DO CONSOLE WITH "WEBCONNECTIONWEBSERVER",lcWebPath
   lcUrl = STRTRAN(lcUrl,"localhost/" + lcVirtual,"localhost:5200")
ENDIF



ACTIVATE SCREEN
CLEAR
lnOldFont = _Screen.FontName
lnOldFontSize =  _Screen.FontSize
_Screen.FontName = "Consolas"
_Screen.FontSize = 19



**********************
*** LAUNCH WEB BROWSER
**********************

lcServerName = "IIS"

? "Running:" 
DO CASE
CASE lcType == "WEBCONNECTIONWEBSERVER"
  ? [DO Launch.prg with "WEBCONNECTIONWEBSERVER"]
  lcServerName = ".NET Core Web Connection Web Server"
CASE ATC("IISEXPRESS",lcType) > 0 
  ? [DO Launch.prg with "IISEXPRESS"]
  lcServerName = "IIS Express"
OTHERWISE  
  ? [DO Launch.prg with "IIS"]
ENDCASE
                        
? ""
? ""
? "Web Server used:"
? lcServerName 

IF lcType == "IISEXPRESS"
   ? "Launched IISExpress with:"
   ? [DO console WITH "IISExpress","..\Web",7000]
   ?
ENDIF
IF lcType == "WEBCONNECTIONWEBSERVER"
   ? "Launched .NET Core Web Server with:"
   ? lcServerCommand
ENDIF

IF !llNoBrowser
    DO CONSOLE WITH "GOURL",lcUrl
    ? "Launching Web Url:" 
    ? lcUrl
    ? 
ENDIF    

***************************************
*** LAUNCH FOXPRO WEB CONNECTION SERVER
***************************************

? "Server executed:"
? "DO " + lcAppName + "Main.prg"

*** Start Web Connection Server
DO ( lcAppName + "Main.prg")

RETURN
