* RELEASE ALL
* SET PROCEDURE TO
* SET CLASSLIB TO

CD "C:\webconnectionprojects\timetrakker\deploy"

SET PATH TO ("..\data")

SET PATH TO ("C:\WEBCONNECTION\FOX\") ADDITIVE
SET PATH TO ("C:\WEBCONNECTION\FOX\classes") ADDITIVE
SET PATH TO ("C:\WEBCONNECTION\FOX\tools") ADDITIVE

